steps:
# 1. Docker Build
- id: "build"
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-docker.pkg.dev/qwiklabs-gcp-04-4302a10f9e66/docker-registry/myimage:$COMMIT_SHA'
    - '.' # Build context is the current directory

# 2. Push to Artifact Registry (This is a valid explicit push step)
- id: "push"
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-docker.pkg.dev/qwiklabs-gcp-04-4302a10f9e66/docker-registry/myimage:$COMMIT_SHA'

images:
# Images to be pushed to the registry
- 'us-docker.pkg.dev/qwiklabs-gcp-04-4302a10f9e66/docker-registry/myimage:$COMMIT_SHA'

# --- TOP-LEVEL CONFIGURATION FIELDS START HERE ---

# MUST be a top-level field, aligned with 'steps' and 'images'.
logsBucket: 'gs://buildlogs-qwiklabs-gcp-04-4302a10f9e66'

# MUST be a top-level field, aligned with 'steps' and 'images'.
options:
  logging: GCS_ONLY
