steps:
# 1. Docker Build
- id: "build"
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-docker.pkg.dev/qwiklabs-gcp-04-4302a10f9e66/docker-registry/myimage:$COMMIT_SHA'
    - '.' # Build context is the current directory

# 2. Push to Artifact Registry (This step is technically optional if using the 'images' field below)
- id: "push"
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-docker.pkg.dev/qwiklabs-gcp-04-4302a10f9e66/docker-registry/myimage:$COMMIT_SHA'

images:
# Use the exact, full path of the image you built and tagged in the steps above.
- 'us-docker.pkg.dev/qwiklabs-gcp-04-4302a10f9e66/docker-registry/myimage:$COMMIT_SHA'
